apps/coaching_app/urls.py
from django.conf.urls import url
from . import views


from django.contrib import admin 
from django.urls import path 
from django.conf import settings 
from django.conf.urls.static import static 
from .views import *

urlpatterns = [
    url(r'^login_page$', views.login_page),
    url(r'^regprocess$', views.user_process),
    url(r'^registration$', views.registration),
    url(r'^loginprocess$', views.login_process),
    url(r'^login$', views.login),
    url(r'^logout$', views.logout),
    url(r'^$', views.home_page),
    url(r'^survey$', views.survey),
    url(r'^survey_reply$', views.survey_reply),
    url(r'^my_account$', views.my_account),
    url(r'^user_account$', views.user_account),
    url(r'^no$', views.no_survey_reply),
    url(r'^user/update/(?P<userid>\w+)$', views.update),
    url(r'^user/edit/(?P<userid>\w+)$', views.edit_account),
    # url(r'^createpost$', views.createpost),
    url(r'^sampleworkout$', views.sampleworkout),
    url(r'^search', views.search),
    # url(r'^createpost$', views.createpost)
    url(r'^search', views.search),
    url(r'^createpost$', views.create_post),
    url(r'^newpost$', views.new_post)
]

# urlpatterns = [ 
#     path('image_upload', post_image_view, name = 'image_upload'), 
#     path('success', success, name = 'success'),
    # path('post_images', display_hotel_images, name = 'post_images'),
# ] 

if settings.DEBUG: 
        urlpatterns += static(settings.MEDIA_URL, 
                              document_root=settings.MEDIA_ROOT)

coaching/urls.py
from django.conf.urls import url, include	# added an import!
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path 

urlpatterns = [
    url(r'^', include('apps.coaching_app.urls')),	
    # path('', include('apps.coaching_app.urls')),
]

apps/coaching_app/models.py
from __future__ import unicode_literals
from django.db import models
import re
from datetime import datetime, timedelta, date
import math


class UserManager(models.Manager):
    def validator(self, postData):
        errors = {}
        EMAIL_REGEX = re.compile(
            r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')
        if len(postData['first_name']) < 2:
            errors["first_name"] = "User's first name should be at least 2 characters"
        if len(postData['last_name']) < 2:
            errors["last_name"] = "User's last name should be at least 2 characters"
        if len(postData['password']) < 8:
            errors["password"] = "User's password should be at least 8 characters"
        if not EMAIL_REGEX.match(postData['email']):
            errors['email'] = ("Invalid email address!")
        if postData['password_confirm'] != postData['password']:
            errors['confirm_pw'] = "Password does not match"
        return errors
    def edit_validator(self, postData):
        errors = {}
        EMAIL_REGEX = re.compile(
            r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')
        if len(postData['first_name']) < 2:
            errors["first_name"] = "User's first name should be at least 2 characters"
        if len(postData['last_name']) < 2:
            errors["last_name"] = "User's last name should be at least 2 characters"
        # if len(postData['password']) < 8:
        #     errors["password"] = "User's password should be at least 8 characters"
        if not EMAIL_REGEX.match(postData['email']):
            errors['email'] = ("Invalid email address!")
        # if postData['password_confirm'] != postData['password']:
        #     errors['confirm_pw'] = "Password does not match"
        return errors


class User(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    username = models.CharField(max_length=250)
    email = models.CharField(max_length=255)
    password = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = UserManager()



class Goal(models.Model):
    goal_title = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    users_goal = models.ManyToManyField(User, related_name="goals")


class Post(models.Model):
    post_title = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    post_pic = models.ImageField(upload_to='images/')
    posted_by = models.ForeignKey(User, related_name="posts", on_delete=models.PROTECT)


    

apps/coaching_app/forms.py
# forms.py 
from django import forms 
from .models import *
  
class PostForm(forms.ModelForm): 
  
    class Meta: 
        model = Post 
        fields = ['post_title', 'description', 'post_pic'] 

apps/coaching_app/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
import bcrypt
from .models import *
from .forms import *


import argparse

from googleapiclient.discovery import build
from googleapiclient.errors import HttpError

# print(build)

developer_key = 'AIzaSyCVuN7GOKmyHIT0xtpd2WTM4n9pEI-zwXQ'
youtube_api_service_name = 'youtube'
youtube_api_version = 'v3'


def home_page(request):
    return render(request, 'coaching_app/index.html')


def login_page(request):
    return render(request, 'coaching_app/login_reg.html')


def user_process(request):
    errors = User.objects.validator(request.POST)
    if len(errors) > 0:
        for key, value in errors.items():
            messages.error(request, value, extra_tags="register")
        return redirect('/login_page#toregister')
    else:
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        username = request.POST["username"]
        email = request.POST["email"]
        matched_user = User.objects.filter(username=request.POST["username"])
        if len(matched_user) > 0:
            messages.error(request, 'Username unavailable',
                           extra_tags="register")
            return redirect('/login_page#toregister')
        pw_hash = bcrypt.hashpw(
            request.POST["password"].encode(), bcrypt.gensalt())
        new_user = User.objects.create(
            first_name=first_name, last_name=last_name, username=username, email=email, password=pw_hash)
        request.session["new_user_id"] = new_user.id
        request.session["username"] = request.POST["username"]
    return redirect('/registration')


def registration(request):
    context = {
        "reg_user": User.objects.get(id=request.session["new_user_id"]),
    }
    return render(request, 'coaching_app/create_profile.html', context)


def login_process(request):
    matched_user = User.objects.filter(username=request.POST['username'])
    print(matched_user)
    if len(matched_user) < 1:
        messages.error(
            request, 'Email or password does not match', extra_tags="login")
        return redirect('/login_page')
    if bcrypt.checkpw(request.POST['password'].encode(), matched_user[0].password.encode()):
        request.session['username'] = request.POST['username']
        return redirect('/login')
    else:
        messages.error(request, 'Email or password do not match',
                       extra_tags="login")
        return redirect('/login_page')
    return redirect('/login_page')


def login(request):
    context = {
        "reg_user": User.objects.filter(username=request.session["username"])[0]
    }
    return render(request, 'coaching_app/everyone_account.html', context)


def logout(request):
    request.session.clear()
    return redirect('/login_page')


def survey(request):
    return render(request, "coaching_app/survey.html")


def survey_reply(request):
    return render(request, "coaching_app/congrats.html")


def my_account(request):
    context = {
        "reg_user": User.objects.filter(username=request.session["username"])[0],
        # "new_user": User.objects.get(id=userid)
    }
    return render(request, "coaching_app/my_account.html", context)


def user_account(request):
    return render(request, "coaching_app/user_account.html")


def no_survey_reply(request):
    return render(request, "coaching_app/no_survey_reply.html")


def update(request, userid):
    errors = User.objects.edit_validator(request.POST)
    user_id = userid
    if len(errors) > 0:
        for key, value in errors.items():
            messages.error(request, value)
        return redirect('/registration')
    matched_user = User.objects.filter(username=request.POST["username"])
    if len(matched_user) > 1:
        messages.error(request, 'Username unavailable')
        return redirect('/registration')
    else:
        updated_user = User.objects.get(id=userid)
        updated_user.first_name = request.POST['first_name']
        updated_user.last_name = request.POST['last_name']
        updated_user.bio = request.POST['bio']
        updated_user.email = request.POST['email']
        updated_user.username = request.POST['username']
        # updated_user.password = request.POST['password']
        updated_user.save()
    return redirect('/user/edit/' + user_id)


def edit_account(request, userid):
    context = {
        "reg_user": User.objects.get(id=request.session["new_user_id"]),
        "new_user": User.objects.get(id=userid)
    }
    return render(request, "coaching_app/my_account.html", context)


def sampleworkout(request):
    return render(request, "coaching_app/sample_workout.html")


def search(request):
    print('SEARCH ITEM', request.POST['search']),
    search = request.POST['search'],
    return redirect('/item')


def create_post(request):
    if request.method == 'POST': 
        form = PostForm(request.POST, request.FILES) 
  
        if form.is_valid(): 

            post = form.save(commit=False) 
            user = User.objects.filter(username=request.session["username"])[0]     
            post.posted_by = user
            post.save()

            return redirect('success') 
    else: 
        form = PostForm() 
    context = {
        "reg_user": User.objects.filter(username=request.session["username"])[0],
        'form': form
    }
    
    return render(request, "coaching_app/post.html", context)

def new_post(request):
    user = User.objects.get(username=request.session["username"])
    post_created = Post.objects.create(post_title = request.POST['title'], description = request.POST['description'], posted_by=user)
    print("*************")
    print(post_created)
    print("*************")
    return redirect('/my_account')


def post_image_view(request): 

    if request.method == 'POST': 
        form = PostForm(request.POST, request.FILES) 
  
        if form.is_valid(): 
            form.save() 
            return redirect('success') 
    else: 
        form = PostForm() 
    return render(request, 'post.html', {'form' : form}) 
  
  
def success(request): 
    return HttpResponse('successfully uploaded')


# def display_post_images(request): 
  
#     if request.method == 'GET': 
  
#         # getting all the objects of hotel. 
#         Post = Post.objects.all()  
#         return render(request, 'display_post_images.html', {'post_images' : Hotels}) 

apps/coaching_app/templates/coaching_app/Test.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <style>
        .speech-bubble {
            position: relative;
            background: #00daf1;
            border-radius: .4em;
        }

        .speech-bubble:after {
            content: '';
            position: absolute;
            bottom: 0;
            left: 50%;
            width: 0;
            height: 0;
            border: 28px solid transparent;
            border-top-color: #00daf1;
            border-bottom: 0;
            border-left: 0;
            margin-left: -14px;
            margin-bottom: -28px;
        }
    </style>

</head>

<body>
    <p class="speech-bubble" class="speech-bubble:after">HI</p>
</body>

</html>

apps/coaching_app/templates/coaching_app/congrats.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Bare - Start Bootstrap Template</title>

  <!-- Bootstrap core CSS -->

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  

  <link href="css/bootstrap.min.css" rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
    <div class="container">
      <a class="navbar-brand" href="#">Congratulations!</a>
    </div>
  </nav>

  <!-- Page Content -->
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h1 class="mt-5">Your email is on the way!</h1>
        <p class="lead">We hope you decide to join our team!</p>
        <div>
          <form style="display:inline-block" action="/login_page#toregister">
            <button type="submit" class="btn btn-success">Create a free Account!</button>
          </form>
          <form style="display:inline-block" action="/">
            <button type="submit" class="btn btn-dark">Back to Home</button>
          </form>
        </div>
      </div>
    </div>
  </div>

  <!-- Bootstrap core JavaScript -->
  <script src="vendor/jquery/jquery.slim.min.js"></script>
  <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

</body>

</html>

apps/coaching_app/templates/coaching_app/create_profile 2.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


  <title>Modern Business - Start Bootstrap Template</title>

  <!-- Bootstrap core CSS -->
  <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="css/modern-business.css" rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="index.html">Start Bootstrap</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
        data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
        aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="about.html">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="services.html">Services</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="contact.html">Contact</a>
          </li>
          <li class="nav-item active dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownPortfolio" data-toggle="dropdown"
              aria-haspopup="true" aria-expanded="false">
              Portfolio
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownPortfolio">
              <a class="dropdown-item" href="portfolio-1-col.html">1 Column Portfolio</a>
              <a class="dropdown-item" href="portfolio-2-col.html">2 Column Portfolio</a>
              <a class="dropdown-item" href="portfolio-3-col.html">3 Column Portfolio</a>
              <a class="dropdown-item" href="portfolio-4-col.html">4 Column Portfolio</a>
              <a class="dropdown-item active" href="portfolio-item.html">Single Portfolio Item</a>
            </div>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownBlog" data-toggle="dropdown"
              aria-haspopup="true" aria-expanded="false">
              Blog
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownBlog">
              <a class="dropdown-item" href="blog-home-1.html">Blog Home 1</a>
              <a class="dropdown-item" href="blog-home-2.html">Blog Home 2</a>
              <a class="dropdown-item" href="blog-post.html">Blog Post</a>
            </div>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownBlog" data-toggle="dropdown"
              aria-haspopup="true" aria-expanded="false">
              Other Pages
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownBlog">
              <a class="dropdown-item" href="full-width.html">Full Width Page</a>
              <a class="dropdown-item" href="sidebar.html">Sidebar Page</a>
              <a class="dropdown-item" href="faq.html">FAQ</a>
              <a class="dropdown-item" href="404.html">404</a>
              <a class="dropdown-item" href="pricing.html">Pricing Table</a>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </nav>




  <div class="container">
    <h1>Edit Profile</h1>
    <hr>
    <div class="row">
      <!-- left column -->
      <div class="col-md-3">
        <div class="text-center">
          <img src="//placehold.it/100" class="avatar img-circle" alt="avatar">
          <h6>Upload a different photo...</h6>

          <input type="file" class="form-control">
        </div>
      </div>

      <!-- edit form column -->
      <div class="col-md-9 personal-info">
        <div class="alert alert-info alert-dismissable">
          <a class="panel-close close" data-dismiss="alert">×</a>
          <i class="fa fa-coffee"></i>
          This is an <strong>.alert</strong>. Use this to show important messages to the user.
        </div>
        <h3>Personal info</h3>

        {% if messages %}
        <ul class="messages">
          {% for message in messages %}
          <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
          {% endfor %}
        </ul>
        {% endif %}
        

        <form action="/user/update/{{reg_user.id}}" method="POST" class="form-horizontal" role="form">
          {% csrf_token %}
          <div class="form-group">
            <label class="col-lg-3 control-label">First name:</label>
            <div class="col-lg-8">
              <input name="first_name" class="form-control" type="text" value={{reg_user.first_name}}>
            </div>
          </div>
          <div class="form-group">
            <label class="col-lg-3 control-label">Last name:</label>
            <div class="col-lg-8">
              <input name="last_name" class="form-control" type="text" value={{reg_user.last_name}}>
            </div>
          </div>
          <div class="form-group">
            <label class="col-lg-3 control-label">Bio:</label>
            <div class="col-lg-8">
              <input name="bio" class="form-control" type="text" value="">
            </div>
          </div>
          <div class="form-group">
            <label class="col-lg-3 control-label">Email:</label>
            <div class="col-lg-8">
              <input name="email" class="form-control" type="text" value={{reg_user.email}}>
            </div>
          </div>
          <div class="form-group">
            <label class="col-lg-3 control-label">Fitness Goal:</label>
            <div class="col-lg-8">
              <div class="ui-select">
                <select name="user_goal" id="user_goal" class="form-control">
                  <option>Gain Muscle</option>
                  <option>Toning</option>
                  <option>Weight Loss</option>
                </select>
              </div>
            </div>
          </div>
          <div class="form-group">
            <label class="col-md-3 control-label">Username:</label>
            <div class="col-md-8">
              <input name="username" class="form-control" type="text" value={{reg_user.username}}>
            </div>
          </div>
          <!-- <div class="form-group">
            <label class="col-md-3 control-label">Password:</label>
            <div class="col-md-8">
              <input name="password" class="form-control" type="password" value="123456789">
            </div>
          </div>
          <div class="form-group">
            <label class="col-md-3 control-label">Confirm password:</label>
            <div class="col-md-8">
              <input name="password_confirm" class="form-control" type="password" value="123456789">
            </div>
          </div> -->
          <div class="form-group">
            <label class="col-md-3 control-label"></label>
            <div class="col-md-8">
              <input type="submit" class="btn btn-primary" value="Save Changes">
              <span></span>
              <input type="reset" class="btn btn-default" value="Cancel">
            </div>
          </div>
        </form>

      </div>
    </div>
  </div>
  <hr>


  </div>
  <!-- /.container -->

  <!-- Footer -->
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Your Website 2019</p>
    </div>
    <!-- /.container -->
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="vendor/jquery/jquery.min.js"></script>
  <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

</body>

</html>

apps/coaching_app/templates/coaching_app/home_page.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/home_page_style.css' %}">
    <title>Fitness Inspo</title>
</head>

<body>
    <div class="container">
        <div>
            <h4>Want a free account?</h4>
            <a href="/login_page">Sign up!</a>
            <a href="/login_page">Login</a>
        </div>
        <div class="right-side">
            <h2>Are you ready to join a challenge?</h2>
            <input type="radio" value="Yes">Yes, bring it on
            <input type="radio" value="No">No, I want my mommy
        </div>
        <div class="left-side">
            <h3>Who am I?</h3>
        </div>
        <div class="left-side2">
            <h3>Program intro</h3>
        </div>
        <div class="left-side3">
            <h3>Sample workout</h3>
        </div>


</body>

</html>

apps/coaching_app/templates/coaching_app/my_account.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Modern Business - Start Bootstrap Template</title>

  {% load static %}
  <link rel="stylesheet" href="{% static 'css/modern-business.css' %}">
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  <!-- Bootstrap core CSS -->
  <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="css/modern-business.css" rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="index.html">Start Bootstrap</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
        data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
        aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="/">BB Coach</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/logout">Logout</a>
          </li>
      </div>
  </nav>

  <!-- Page Content -->
  <div class="container">

    <!-- Page Heading/Breadcrumbs -->
    <h1 class="mt-4 mb-3">Welcome {{reg_user.first_name}}</h1>

    <ol class="breadcrumb">
      <li class="breadcrumb-item">
        <a href="/login">Home</a>
      </li>
      <li class="breadcrumb-item">
        <a href="/login">Notifications</a>
      </li>
      <li class="breadcrumb-item">
        <a href="/createpost">Create a Post</a>
      </li>
      <li class="breadcrumb-item active">{{reg_user.username}}</li>
    </ol>

    <!-- Portfolio Item Row -->
    <div class="row">

      <div class="col-md-8" style="background-image: url('/static/post.jpg'); height: 400px">
        <!-- <img class="img-fluid" src="post.jpg" alt="abs"> -->
      </div>

      <div class="col-md-4">
        <h3 class="my-3">3-minute Abs Workout</h3>
        <p>This is my 3-minute abs workout for runners. Feeling refreshed! #TGIF</p>
      </div>

    </div>
    <!-- /.row -->

    <!-- Related Projects Row -->
    <h3 class="my-4">My Fitness Posts</h3>

    <div class="row">

      <div class="col-md-3 col-sm-6 mb-4">
        <a href="#">
          <img class="img-fluid" src="http://placehold.it/500x300" alt="">
        </a>
      </div>

      <div class="col-md-3 col-sm-6 mb-4">
        <a href="#">
          <img class="img-fluid" src="http://placehold.it/500x300" alt="">
        </a>
      </div>

      <div class="col-md-3 col-sm-6 mb-4">
        <a href="#">
          <img class="img-fluid" src="http://placehold.it/500x300" alt="">
        </a>
      </div>

      <div class="col-md-3 col-sm-6 mb-4">
        <a href="#">
          <img class="img-fluid" src="http://placehold.it/500x300" alt="">
        </a>
      </div>

    </div>
    <!-- /.row -->

  </div>
  <!-- /.container -->

  <!-- Footer -->
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Your Website 2019</p>
    </div>
    <!-- /.container -->
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="vendor/jquery/jquery.min.js"></script>
  <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

</body>

</html>

apps/coaching_app/templates/coaching_app/survey.html
<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
{% load static %}
<script src="{% static 'js/script.js' %}"></script>
<!------ Include the above in your HEAD tag ---------->

<div class="container">

    <div id="signupbox" style=" margin-top:50px" class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
        <div class="panel panel-info">
            <div class="panel-heading">
                <div class="panel-title">Contact me!</div>
            </div>
            <div class="panel-body">
                <form action="/survey_reply" method="POST">
                    {% csrf_token %}

                    <div id="div_id_username" class="form-group required">
                        <label for="id_username" class="control-label col-md-4  requiredField"> First name<span
                                class="asteriskField">*</span> </label>
                        <div class="controls col-md-8 ">
                            <input class="input-md  textinput textInput form-control" id="id_username" maxlength="30"
                                name="firstname" placeholder="Lovely" style="margin-bottom: 10px" type="text" />
                        </div>
                    </div>
                    <div id="div_id_username" class="form-group required">
                        <label for="id_username" class="control-label col-md-4  requiredField"> Last name<span
                                class="asteriskField">*</span> </label>
                        <div class="controls col-md-8 ">
                            <input class="input-md  textinput textInput form-control" id="id_username" maxlength="30"
                                name="lastname" placeholder="Lover" style="margin-bottom: 10px" type="text" />
                        </div>
                    </div>
                    <div id="div_id_email" class="form-group required">
                        <label for="id_email" class="control-label col-md-4  requiredField"> E-mail<span
                                class="asteriskField">*</span> </label>
                        <div class="controls col-md-8 ">
                            <input class="input-md emailinput form-control" id="id_email" name="email"
                                placeholder="Your current email address" style="margin-bottom: 10px" type="email" />
                        </div>
                    </div>
                    <div id="div_id_gender" class="form-group required">
                        <label for="id_gender" class="control-label col-md-4  requiredField"> Preference<span
                                class="asteriskField">*</span> </label>
                        <div class="controls col-md-8 " style="margin-bottom: 10px">
                            <label class="radio-inline"> <input type="radio" name="gender" id="id_gender_1" value="M"
                                    style="margin-bottom: 10px">Vegan</label>
                            <label class="radio-inline"> <input type="radio" name="gender" id="id_gender_2" value="F"
                                    style="margin-bottom: 10px">Whey </label>
                        </div>
                    </div>
                    <div>
                        <label class="control-label col-md-4">Comments</label>
                        <div class="controls col-md-8 " style="margin-bottom: 10px">
                            <div class="controls col-md-8 ">
                                <input class="input-md textinput textInput form-control" name="comments"
                                    placeholder="Comment/Questions" style="margin-bottom: 10px" type="comment" />
                            </div>
                        </div>
                    </div>


                    <div class="form-group">
                        <div class="aab controls col-md-4 "></div>
                        <div class="controls col-md-8 ">
                            <input type="submit" name="submit" class="btn btn-primary btn btn-info"
                                id="submit-id-signup" />
                        </div>
                    </div>

                    <!-- </form> -->

                </form>
            </div>
        </div>
    </div>
</div>






</div>